name: CI

on:
  push:
    branches: ["main", "15-cicd"]
  pull_request:
    branches: ["main", "15-cicd"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build || echo "No build script defined, skipping."

  systemtest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: System Test Demo
        run: echo "System test would run here, after build."

  deploy:
    needs: systemtest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token $VERCEL_TOKEN --confirm
